### ISSUE TITLE
Use a Fork from Original Repo for Persian-HIG

### ISSUE THREAD

**Issue by shervinafshar** [persian-computing/persian-computing.github.io#3]
I'm thankful that you forked Persian-HIG repo under P-C org, but I would like to ask you to fork the original rather than forking your own user fork. This applies to some other repositories on that page from other users, but I leave the decision for the rest of them to you.

![image](https://user-images.githubusercontent.com/875962/36645863-d315695e-1a23-11e8-90b0-61016ee48cf1.png)

Thanks.

**Comment by behnam** [comment]
Thanks for the report. Initially I had many repos forked under my personal account for archival, and then tried to move them to P-C. I deleted mine and now the upstream is shown.

Side note: The good thing is that GH always shows the complete fork tree, so it never gets lost. But the bad thing is that generally it's not a good way for archival, because if the root deletes the project, the downstream forks can easily be affected and go out of reach.

And on a more direct note: let me know if you feel like moving it to P-C. I can set up the access, if you like to.

**Comment by shervinafshar** [comment]
Absolutely. P-C is a good home for it. I'll have it moved.

↪ Shervin

**Comment by shervinafshar** [comment]
Could you unfork the repo so I could move it. Can't do when it exists and
don't have the permission to remove.

↪ Shervin

**Comment by behnam** [comment]
Cool! Done!

**Comment by shervinafshar** [comment]
Okay. This is becoming a pain in the neck.

[image: Inline image 1]

I have already added you as a collaborator on Persian-HIG. See if you could
move it.

↪ Shervin

On Tue, Feb 27, 2018 at 8:06 AM, Behnam Esfahbod ❄ <notifications@github.com

**Comment by behnam** [comment]
The image doesn't show up in GH, so not sure what happened there.

I tried, but looks like I don't have admin access to the repo to move.

I've updated organization member policy to allow creation of repos. Would you please try again?
